[package]
name = "unicode-segmentation-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unicode-segmentation = "1.11.0"
wasm-bindgen = "0.2.93"

[profile.release]
lto = true
